### PR TITLE
Bold keywords -> non italic

### PR DESCRIPTION
**Pull request by dayeya**
I've created this pull request to change the bold keywords and contestants into non-italic.
Maybe could you make it an option?

### CODE REVIEW

**Comment by AnksioXD** [comment]
do you want the fontStyle of "Bold Keywords" and "Bold Constants" to be none? coz non-italic is not a valid property

**Comment by dayeya** [comment]
Yes. I have now created a pull request and changed the "Bold Keywords" and "Bold Constants" font Style to "" instead of "bold".
If you can open an option for that it would be cool. for now, I'm glad Im found this theme!

**Comment by AnksioXD** [comment]
while youre at it can you tell me whether i should keep #ffdd33 or #949BB0 (tsoding original) colors for html tags
paste this in your settings.json to preview:
```json
"editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "name": "Tags",
        "scope": "entity.name.tag",
        "settings": {
          "foreground": "#ffdd33",
          "foreground": "#949BB0"
        }
      },
    ]
 }
```

**Comment by dayeya** [comment]
For me, I would like to keep #ffdd33.

**Comment by AnksioXD** [comment]
alrighty then new version of theme has been pushed to marketplace.

**Comment by dayeya** [comment]
Thats amazing

**Pull request closed without merging**
